### ISSUE TITLE
Prepare a zip file with code and resources for the submission

### ISSUE THREAD

**Issue by dachafra** [SDM-TIB/ISWC2020RMLFnQ#1]
@eiglesias34 please go ahead and contact me if you need any help

- README/Instructions on how to run the experiments
- Dockerfile and docker-compose for all the approaches
- Downloading script for the input data (we can upload a zip file to google drive)
- Mappings
- Running scripts
- DOI for the engine with Zenodo

**Comment by samiscoding** [comment]
Mappings are cleaned up and data is added into the repository. feel free to move it to the drive if it sounds more convenient.

**Comment by dachafra** [comment]
zip ready and also uploaded here
