### ISSUE TITLE
Parse error when running experiments

### ISSUE THREAD

**Issue by kmitd** [SDM-TIB/ISWC2020RMLFnQ#6]
Hi,

I am trying to reproduce your experiments (ISWC reproducibility branch) but the `run.sh` script throws a parse error 
```(standard_in) 1: illegal character: N
(standard_in) 1: illegal character: N
(standard_in) 1: parse error
```
at each iteration. 

This propagates through the other scripts (the `run-rdb.sh` script outputs the following: 

```
---------Experiments over RDB with SDM-RDFizer 
(note that experiments with complex_sameFunction10_RDB_5millionRecords.ttl could not finish in SDM-RDFizer configuration ---------
sed: 1: "config-rdb-funmap.ini": command c expects \ followed by text
sed: 1: "config-rdb-SDM.ini": command c expects \ followed by text
```

preventing result outputs to be generated.

Could you help me with that?

Cheers,

ilaria

**Comment by dachafra** [comment]
Hi @kmitd,
Could you tell us what is the OS you are using to reproduce the experiments? Is Mac OS or Linux-based?

Thanks!

**Comment by kmitd** [comment]
yes sure. Running on my Macbook Pro Mac OS (mojave), 16GB mem

**Comment by dachafra** [comment]
yes, that is the problem! the scripts are created to be run in an ubuntu machine (e.g., the behaviour and syntaxis of the `sed` command are not the same in Mac OS as they are in Ubuntu) and also with other commands that we are using in the scripts. The scripts can be adapted to be run in a Mac OS based system, but it would require a bit of time. If you don't have access to any Ubuntu-based machine one option could be to encapsulate all in a ubuntu docker image: https://hub.docker.com/_/ubuntu

**Comment by kmitd** [comment]
OK, it'd be good to add this information to the readme perhaps. I will also try to look at the `sed` calls to see if it is faster to modify it myself ;)

**Comment by dachafra** [comment]
I think it is already provided in the readme ;-) Thanks for your questions!
![image](https://user-images.githubusercontent.com/12400271/96453678-1921e200-121b-11eb-8f24-9a449094bc5e.png)

**Comment by kmitd** [comment]
thanks, my bad.
